### ISSUE TITLE
Error Handling in Selenium section

### ISSUE THREAD

**Issue by sharedphysics** [sharedphysics/Crawwwly#4]
Issue 1:

Wasn't able to open the site. Selenium failed to capture.
```

Now scanning: https://www.landmarkhealth.org/

Traceback (most recent call last):
  File "crawwwly-selenium.py", line 33, in <module>
    driver.get(args.url)
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Reached error page: about:neterror?e=nssFailure2&u=https%3A//www.landmarkhealth.org/&c=UTF-8&d=The%20connection%20to%20www.landmarkhealth.org%20was%20interrupted%20while%20the%20page%20was%20loading.

  -- File saved as Landmark-10202020-1132.png
Traceback (most recent call last):
  File "crawwwly.py", line 70, in <module>
    png = Image.open('results/' + simplename + '/' + outputfilename)
  File "/usr/local/lib/python3.8/site-packages/PIL/Image.py", line 2843, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'results/Landmark/Landmark-10202020-1132.png'

```

**Comment by sharedphysics** [comment]
Seemingly fixed with https://github.com/sharedphysics/Crawwwly/commit/f3490086d5f7b553c3a77e136ae00535876fc0dd
